import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Hero Section
    'hero.title': 'XMRT Economy',
    'hero.subtitle': 'Mobile Mining Democracy • AI-Human Collaboration • Privacy as a Fundamental Right',
    'hero.tag.smartphone': '📱 Smartphone Mining',
    'hero.tag.ai': '🤖 Autonomous AI',
    'hero.tag.privacy': '🔐 Privacy First',
    'hero.tag.mesh': '🕸️ Mesh Networks',
    
    // Mining Section
    'mining.title': 'Mobile Mining Democracy in Action',
    'mining.subtitle': 'Every smartphone becomes a tool of economic empowerment • Live data from the mesh network',
    
    // AI Section
    'ai.title': 'Eliza AI: Autonomous DAO Operator',
    'ai.subtitle': 'The philosophical AI guide embodying XMRT principles • Voice-enabled for mobile-first experience • 95%+ autonomous decision-making capabilities',
    
    // Actions Section
    'actions.title': 'Join the Infrastructure Revolution',
    'actions.subtitle': 'Transform your smartphone into a mining node • Participate in true decentralized governance • Build the mesh network',
    'actions.start.mining': 'Start Mobile Mining',
    'actions.join.dao': 'Join DAO Governance',
    
    // Calculator
    'calculator.title': 'Smartphone Mining Calculator',
    'calculator.subtitle': 'Calculate your mobile mining potential • ARM processor optimization • Thermal management included',
    
    // Feature Cards
    'feature.mobile.title': 'Mobile Mining Democracy',
    'feature.mobile.description': 'Transform smartphones into tools of economic empowerment',
    'feature.mobile.tag.arm': '📱 ARM Optimized',
    'feature.mobile.tag.battery': '🔋 Battery Safe',
    'feature.mobile.tag.thermal': '🌡️ Thermal Managed',
    
    'feature.dao.title': 'Autonomous DAO Governance',
    'feature.dao.description': '95%+ autonomous AI with verifiable compute and community oversight',
    'feature.dao.executives': 'AI Executives',
    'feature.dao.compute': 'Verifiable Compute',
    'feature.dao.status.active': 'Active',
    'feature.dao.status.certified': 'Certified',
    
    'feature.privacy.title': 'Privacy-First Infrastructure',
    'feature.privacy.description': 'Mesh networks, private transactions, and censorship-resistant communication',
    'feature.privacy.mesh': 'Mesh Network',
    'feature.privacy.privacy': 'Privacy',
    'feature.privacy.status.building': 'Building',
    'feature.privacy.status.fundamental': 'Fundamental',
    
    // Navigation
    'nav.home': 'Home',
    'nav.board': 'Board',
    'nav.council': 'Council',
    'nav.earn': 'Earn',
    'nav.governance': 'Governance',
    'nav.enterprise': 'Enterprise',
    'nav.licensing': 'Licensing',
    'nav.admin': 'Admin',
    'nav.treasury': 'Treasury',
    'nav.credentials': 'Credentials',
    'nav.profile': 'Profile',
    'nav.dashboard': 'Dashboard',
    
    // Common Buttons
    'button.submit': 'Submit',
    'button.cancel': 'Cancel',
    'button.save': 'Save',
    'button.delete': 'Delete',
    'button.edit': 'Edit',
    'button.close': 'Close',
    'button.confirm': 'Confirm',
    'button.back': 'Back',
    'button.next': 'Next',
    'button.continue': 'Continue',
    'button.finish': 'Finish',
    'button.start': 'Start',
    'button.stop': 'Stop',
    'button.pause': 'Pause',
    'button.resume': 'Resume',
    'button.upload': 'Upload',
    'button.download': 'Download',
    'button.share': 'Share',
    'button.copy': 'Copy',
    'button.clear': 'Clear',
    'button.reset': 'Reset',
    'button.search': 'Search',
    'button.filter': 'Filter',
    'button.sort': 'Sort',
    'button.refresh': 'Refresh',
    'button.reload': 'Reload',
    'button.login': 'Login',
    'button.logout': 'Logout',
    'button.signup': 'Sign Up',
    'button.signin': 'Sign In',
    'button.connect': 'Connect',
    'button.disconnect': 'Disconnect',
    'button.approve': 'Approve',
    'button.reject': 'Reject',
    'button.send': 'Send',
    'button.receive': 'Receive',
    'button.claim': 'Claim',
    'button.stake': 'Stake',
    'button.unstake': 'Unstake',
    'button.vote': 'Vote',
    'button.propose': 'Propose',
    'button.view': 'View',
    'button.details': 'Details',
    'button.more': 'More',
    'button.less': 'Less',
    'button.expand': 'Expand',
    'button.collapse': 'Collapse',
    'button.yes': 'Yes',
    'button.no': 'No',
    'button.ok': 'OK',
    'button.got.it': 'Got it',
    'button.learn.more': 'Learn More',
    'button.get.started': 'Get Started',
    'button.try.now': 'Try Now',
    'button.buy.now': 'Buy Now',
    'button.add': 'Add',
    'button.remove': 'Remove',
    'button.update': 'Update',
    'button.create': 'Create',
    'button.deploy': 'Deploy',
    'button.verify': 'Verify',
    'button.dashboard': 'Go to Dashboard',
    'button.preview': 'Preview',
    'button.export': 'Export',
    'button.import': 'Import',
    
    // Common Labels
    'label.name': 'Name',
    'label.email': 'Email',
    'label.password': 'Password',
    'label.username': 'Username',
    'label.address': 'Address',
    'label.wallet': 'Wallet',
    'label.balance': 'Balance',
    'label.amount': 'Amount',
    'label.total': 'Total',
    'label.status': 'Status',
    'label.type': 'Type',
    'label.date': 'Date',
    'label.time': 'Time',
    'label.description': 'Description',
    'label.title': 'Title',
    'label.category': 'Category',
    'label.tags': 'Tags',
    'label.price': 'Price',
    'label.quantity': 'Quantity',
    'label.available': 'Available',
    'label.pending': 'Pending',
    'label.completed': 'Completed',
    'label.failed': 'Failed',
    'label.active': 'Active',
    'label.inactive': 'Inactive',
    'label.enabled': 'Enabled',
    'label.disabled': 'Disabled',
    'label.online': 'Online',
    'label.offline': 'Offline',
    'label.connected': 'Connected',
    'label.disconnected': 'Disconnected',
    'label.loading': 'Loading...',
    'label.processing': 'Processing...',
    'label.success': 'Success',
    'label.error': 'Error',
    'label.warning': 'Warning',
    'label.info': 'Info',
    
    // Messages
    'message.success': 'Operation completed successfully',
    'message.error': 'An error occurred',
    'message.loading': 'Loading, please wait...',
    'message.no.data': 'No data available',
    'message.coming.soon': 'Coming soon',
    'message.under.construction': 'Under construction',
    'message.not.found': 'Not found',
    'message.unauthorized': 'Unauthorized access',
    'message.forbidden': 'Access forbidden',
    'message.server.error': 'Server error',
    'message.network.error': 'Network error',
    'message.timeout': 'Request timeout',
    'message.invalid.input': 'Invalid input',
    'message.required.field': 'This field is required',
    'message.confirm.action': 'Are you sure you want to proceed?',
    'message.unsaved.changes': 'You have unsaved changes',
    'message.copied': 'Copied to clipboard',
    'message.saved': 'Changes saved',
    'message.deleted': 'Deleted successfully',
    
    // Treasury Page
    'treasury.title': 'XMRT Treasury',
    'treasury.description': 'Purchase crypto and view treasury statistics',
    'treasury.purchase.title': 'Purchase Crypto',
    'treasury.stats.title': 'Treasury Statistics',
    'treasury.stats.tvl': 'Total Value Locked',
    'treasury.stats.contributors': 'Contributors',
    
    // Mining Calculator
    'calculator.info.title': 'MobileMonero Information',
    'calculator.info.description': 'MobileMonero.com is the first mobile-first Monero mining platform designed for smartphones and tablets.',
    'calculator.info.empowering': 'Empowering users to participate in cryptocurrency mining using ARM processors.',
    'calculator.mining.title': 'MobileMonero Mining Calculator',
    'calculator.hashrate.label': 'Device Hashrate',
    'calculator.devices.label': 'Number of Mining Devices',
    'calculator.price.label': 'Monero Price (USD)',
    'calculator.network.title': 'Network Statistics',
    'calculator.network.hashrate': 'Total Network Hashrate',
    'calculator.network.share': 'Your Network Share',
    'calculator.network.price': 'XMR Price',
    'calculator.earnings.title': 'Projected Earnings',
    'calculator.earnings.daily': 'Daily',
    'calculator.earnings.monthly': 'Monthly',
    'calculator.earnings.yearly': 'Yearly',
    'calculator.disclaimer': 'These calculations are estimates based on current network difficulty and may vary significantly. Actual mining results depend on device performance, network conditions, and market factors.',
    
    // Mining Stats
    'stats.title': 'Live Mining Statistics',
    'stats.hashrate': 'Current Hashrate',
    'stats.shares': 'Valid Shares',
    'stats.invalid.shares': 'Invalid Shares',
    'stats.amount.due': 'Amount Due',
    'stats.amount.paid': 'Amount Paid',
    'stats.transactions': 'Transactions',
    'stats.last.hash': 'Last Hash',
    'stats.total.hashes': 'Total Hashes',
    'stats.status.online': 'Online',
    'stats.status.offline': 'Offline',
    'stats.last.update': 'Last Update',
    'stats.retry': 'Retry Connection',
    'stats.demo.mode': 'Demo Mode',
    'stats.ago': 'ago',
    
    // Chat Interface
    'chat.error.microphone': 'Unable to access microphone',
    'chat.error.connection': 'Connection error',
    'chat.error.network': 'Network error',
    'chat.status.connecting': 'Connecting...',
    'chat.status.connected': 'Connected',
    'chat.status.disconnected': 'Disconnected',
    'chat.status.listening': 'Listening...',
    'chat.status.speaking': 'Speaking...',
    'chat.button.start': 'Start Conversation',
    'chat.button.stop': 'Stop',
    'chat.button.retry': 'Retry',
    'chat.permissions.needed': 'Microphone permission needed',
    
    // DAO Tabs
    'dao.tabs.members': 'Members',
    'dao.tabs.xmrt': 'XMRT',
    'dao.tabs.governance': 'Governance',
    'dao.tabs.treasury': 'Treasury',
    'dao.tabs.proposals': 'Proposals',
    'dao.tabs.discussions': 'Discussions',
    
    // XMRT Faucet
    'faucet.title': 'XMRT Token Faucet',
    'faucet.description': 'Claim free XMRT tokens on Sepolia testnet',
    'faucet.network.status': 'Network Status',
    'faucet.network.correct': 'Connected to Sepolia',
    'faucet.network.wrong': 'Switch to Sepolia Testnet',
    'faucet.claim.amount': 'Claim Amount',
    'faucet.claim.status': 'Claim Status',
    'faucet.claim.available': 'Available to claim',
    'faucet.claim.cooldown': 'Cooldown active',
    'faucet.claim.button': 'Claim XMRT',
    'faucet.claim.next': 'Next claim available in',
    'faucet.success': 'Successfully claimed XMRT tokens!',
    'faucet.error': 'Failed to claim tokens. Please try again.',
    'faucet.error.network': 'Please connect to Sepolia testnet first.',
    
    // Mobile Monero Calculator Info Sections
    'calculator.info.how.works': 'How It Works',
    'calculator.info.how.works.point1': 'Advanced mobile processors mine Monero optimally',
    'calculator.info.how.works.point2': 'SSB (Solid State Battery) enables sustained 3-5+ KH/s',
    'calculator.info.how.works.point3': 'Mining rewards fund XMRT DAO operations',
    'calculator.info.how.works.point4': 'Decentralized network of high-performance mobile miners',
    'calculator.info.how.works.point5': 'ARM optimization for maximum efficiency',
    
    'calculator.info.dao.benefits': 'DAO Benefits',
    'calculator.info.dao.benefits.point1': 'Self-sustaining treasury through mining revenue',
    'calculator.info.dao.benefits.point2': 'Democratic governance powered by mining participants',
    'calculator.info.dao.benefits.point3': 'Environmental efficiency through mobile devices',
    'calculator.info.dao.benefits.point4': 'Global accessibility without specialized hardware',
    
    // Workflow Steps
    'workflow.title': 'Asset Creation Steps',
    'workflow.description': 'Follow these steps to create your {type} asset',
    'workflow.start': 'Start Creating',
    'workflow.image.step1': 'Create a base ERC-721 or ERC-1155 contract for optimal gas efficiency',
    'workflow.image.step2': 'Upload your image file (PNG, JPG, GIF)',
    'workflow.image.step3': 'Set image properties (dimensions, resolution)',
    'workflow.image.step4': 'Add metadata (title, description, attributes)',
    'workflow.image.step5': 'Preview your NFT',
    'workflow.code.step1': 'Deploy a factory contract for efficient contract deployment',
    'workflow.code.step2': 'Upload or paste your smart contract code',
    'workflow.code.step3': 'Configure contract parameters',
    'workflow.code.step4': 'Test contract functionality',
    'workflow.code.step5': 'Deploy and verify contract',
    'workflow.document.step1': 'Initialize an ERC-721 contract with document management features',
    'workflow.document.step2': 'Upload your document (PDF, DOC)',
    'workflow.document.step3': 'Set access permissions',
    'workflow.document.step4': 'Add version control settings',
    'workflow.document.step5': 'Configure sharing options',
    'workflow.audio.step1': 'Set up an ERC-721 contract optimized for audio NFTs',
    'workflow.audio.step2': 'Upload your audio file (MP3, WAV)',
    'workflow.audio.step3': 'Set audio properties (bitrate, duration)',
    'workflow.audio.step4': 'Add track information',
    'workflow.audio.step5': 'Configure playback settings',
    'landing.hero.title.part1': 'Replace Your',
    'landing.hero.title.part2': 'C-Suite',
    'landing.hero.title.part3': 'Not Your Workers',
    'landing.hero.subtitle': 'AI Executive Council that saves $12.4M annually while enabling 41% salary increases for your employees.',
    'landing.hero.start.trial': 'Start Free Trial',
    'landing.hero.watch.demo': 'Watch Demo',
    'landing.stats.savings': 'Average C-Suite Savings',
    'landing.stats.salary': 'Employee Salary Increase',
    'landing.stats.functions': 'Autonomous Functions',
    'landing.stats.operations': 'Always-On Operations',
    'landing.executives.title': 'Meet Your AI Executive Council',
    'landing.executives.subtitle': 'Five specialized AI executives work together 24/7, making strategic decisions and executing autonomous workflows.',
    'landing.benefits.title': 'Why Choose Suite AI?',
    'landing.benefits.subtitle': 'Ethical AI that empowers workers, not replaces them.',
    'landing.benefits.cost.title': 'Massive Cost Savings',
    'landing.benefits.cost.desc': 'Average $12.4M saved by replacing expensive C-suite salaries with AI executives.',
    'landing.benefits.empowerment.title': 'Employee Empowerment',
    'landing.benefits.empowerment.desc': 'Savings redistributed as 41% average salary increases for workers.',
    'landing.benefits.autonomous.title': 'Autonomous Operations',
    'landing.benefits.autonomous.desc': '120+ edge functions execute tasks 24/7 without human intervention.',
    'landing.trial.title': 'to start your free trial',
    'landing.trial.no.card': 'No credit card required',
    'landing.trial.cta': 'Get Started Now',
    'landing.how.title': 'How It Works',
    'landing.how.subtitle': 'Get started in minutes, not months.',
    'landing.how.step1.title': 'Sign Up',
    'landing.how.step1.desc': 'Create your account in seconds with Google',
    'landing.how.step2.title': 'Chat with Executives',
    'landing.how.step2.desc': 'Describe your needs to AI council members',
    'landing.how.step3.title': 'Watch It Work',
    'landing.how.step3.desc': 'Autonomous agents execute tasks in real-time',
    'footer.copyright': '© 2026 XMRT-DAO. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'dashboard.visualizer.title': 'Agent & Task Visualizer',
    'dashboard.activity.title': 'System Activity',
    'dashboard.activity.live': 'Live',
    'hero.banner.enterprise.title': 'Enterprise AI Automation',
    'hero.banner.enterprise.subtitle': 'Intelligent systems that work while you sleep',
    'hero.banner.functions.title': '120+ Edge Functions',
    'hero.banner.functions.subtitle': 'Self-healing, self-optimizing infrastructure',
    'hero.banner.monitoring.title': 'Real-Time Monitoring',
    'hero.banner.monitoring.subtitle': 'Complete visibility into every operation',
    'hero.banner.council.title': 'AI Executive Council',
    'hero.banner.council.subtitle': 'Autonomous governance and decision-making',
    'hero.stats.executions': 'Total Executions',
    'hero.stats.agents': 'Active Agents',
    'hero.stats.health': 'System Health',
    'hero.stats.tasks': 'Active Tasks',
    'hero.activity.title': 'Live Activity Feed',
    'hero.activity.realtime': 'Real-time',
    'licensing.hero.badge': 'Ethical AI Licensing',
    'licensing.hero.title': 'Replace Your C-Suite, Not Your Workers',
    'licensing.hero.subtitle': 'Our AI Executive Board delivers Fortune 500 leadership capabilities at a fraction of the cost. The difference? 100% of savings go to your employees.',
    'licensing.stats.savings': 'Average Annual Savings',
    'licensing.stats.salary': 'Employee Salary Increase',
    'licensing.stats.executives': 'AI Executives (CSO, CTO, CIO, CAO, COO)',
    'licensing.button.apply': 'Start Application',
    'licensing.button.chat': 'Talk to Eliza Instead',
    'licensing.calculator.title': 'Calculate Your Savings',
    'licensing.tiers.title': 'Choose Your License Tier',
    'licensing.tiers.subtitle': 'Every tier includes our ethical commitment: savings from AI executive replacement must be redistributed to employees, not shareholders.',
    'licensing.form.title': 'Corporate License Application',
    'licensing.form.subtitle': 'Complete this form to apply for our ethical AI executive licensing program.',
    'licensing.form.chat.prompt': 'Prefer conversation?',
    'licensing.form.chat.link': 'Let Eliza guide you through it.',
    'licensing.commitment.title': 'Our Ethical Commitment',
    'licensing.commitment.p1': 'The XMRT AI Executive Licensing Model is built on a simple principle: AI should enhance humans, not replace them.',
    'licensing.commitment.p2': 'When you license our AI executives, you agree to our downward redistribution mandate:',
    'licensing.commitment.li1': '100% of executive compensation savings must be redistributed to employees',
    'licensing.commitment.li2': 'No layoffs allowed as a condition of the license',
    'licensing.commitment.li3': 'Quarterly compliance audits ensure adherence',
    'licensing.commitment.li4': 'Public transparency reports showcase your commitment',
    'licensing.commitment.footer': "This isn't just good ethics—it's good business. Companies in our program report higher employee satisfaction, lower turnover, and stronger productivity.",
  },
  es: {
    // Hero Section
    'hero.title': 'Economía XMRT',
    'hero.subtitle': 'Democracia de Minería Móvil • Colaboración IA-Humano • Privacidad como Derecho Fundamental',
    'hero.tag.smartphone': '📱 Minería Móvil',
    'hero.tag.ai': '🤖 IA Autónoma',
    'hero.tag.privacy': '🔐 Privacidad Primero',
    'hero.tag.mesh': '🕸️ Redes Mesh',
    
    // Mining Section
    'mining.title': 'Democracia de Minería Móvil en Acción',
    'mining.subtitle': 'Cada smartphone se convierte en una herramienta de empoderamiento económico • Datos en vivo de la red mesh',
    
    // AI Section
    'ai.title': 'Eliza IA: Operador DAO Autónomo',
    'ai.subtitle': 'La guía filosófica de IA que encarna los principios XMRT • Habilitada por voz para experiencia móvil • Capacidades de toma de decisiones 95%+ autónomas',
    
    // Actions Section
    'actions.title': 'Únete a la Revolución de Infraestructura',
    'actions.subtitle': 'Transforma tu smartphone en un nodo de minería • Participa en gobernanza verdaderamente descentralizada • Construye la red mesh',
    'actions.start.mining': 'Iniciar Minería Móvil',
    'actions.join.dao': 'Unirse a Gobernanza DAO',
    
    // Calculator
    'calculator.title': 'Calculadora de Minería Móvil',
    'calculator.subtitle': 'Calcula tu potencial de minería móvil • Optimización de procesador ARM • Gestión térmica incluida',
    
    // Feature Cards
    'feature.mobile.title': 'Democracia de Minería Móvil',
    'feature.mobile.description': 'Transforma smartphones en herramientas de empoderamiento económico',
    'feature.mobile.tag.arm': '📱 Optimizado ARM',
    'feature.mobile.tag.battery': '🔋 Seguro para Batería',
    'feature.mobile.tag.thermal': '🌡️ Gestionado Térmicamente',
    
    'feature.dao.title': 'Gobernanza DAO Autónoma',
    'feature.dao.description': 'IA 95%+ autónoma con cómputo verificable y supervisión comunitaria',
    'feature.dao.executives': 'Ejecutivos IA',
    'feature.dao.compute': 'Cómputo Verificable',
    'feature.dao.status.active': 'Activo',
    'feature.dao.status.certified': 'Certificado',
    
    'feature.privacy.title': 'Infraestructura Privacidad-Primero',
    'feature.privacy.description': 'Redes mesh, transacciones privadas y comunicación resistente a la censura',
    'feature.privacy.mesh': 'Red Mesh',
    'feature.privacy.privacy': 'Privacidad',
    'feature.privacy.status.building': 'Construyendo',
    'feature.privacy.status.fundamental': 'Fundamental',
    
    // Navigation
    'nav.home': 'Inicio',
    'nav.board': 'Junta',
    'nav.council': 'Consejo',
    'nav.earn': 'Ganar',
    'nav.governance': 'Gobernanza',
    'nav.enterprise': 'Empresa',
    'nav.licensing': 'Licencias',
    'nav.admin': 'Administrador',
    'nav.treasury': 'Tesorería',
    'nav.credentials': 'Credenciales',
    'nav.profile': 'Perfil',
    'nav.dashboard': 'Tablero',
    
    // Common Buttons
    'button.submit': 'Enviar',
    'button.cancel': 'Cancelar',
    'button.save': 'Guardar',
    'button.delete': 'Eliminar',
    'button.edit': 'Editar',
    'button.close': 'Cerrar',
    'button.confirm': 'Confirmar',
    'button.back': 'Atrás',
    'button.next': 'Siguiente',
    'button.continue': 'Continuar',
    'button.finish': 'Finalizar',
    'button.start': 'Iniciar',
    'button.stop': 'Detener',
    'button.pause': 'Pausar',
    'button.resume': 'Reanudar',
    'button.upload': 'Subir',
    'button.download': 'Descargar',
    'button.share': 'Compartir',
    'button.copy': 'Copiar',
    'button.clear': 'Limpiar',
    'button.reset': 'Restablecer',
    'button.search': 'Buscar',
    'button.filter': 'Filtrar',
    'button.sort': 'Ordenar',
    'button.refresh': 'Actualizar',
    'button.reload': 'Recargar',
    'button.login': 'Iniciar sesión',
    'button.logout': 'Cerrar sesión',
    'button.signup': 'Registrarse',
    'button.signin': 'Iniciar sesión',
    'button.connect': 'Conectar',
    'button.disconnect': 'Desconectar',
    'button.approve': 'Aprobar',
    'button.reject': 'Rechazar',
    'button.send': 'Enviar',
    'button.receive': 'Recibir',
    'button.claim': 'Reclamar',
    'button.stake': 'Apostar',
    'button.unstake': 'Retirar',
    'button.vote': 'Votar',
    'button.propose': 'Proponer',
    'button.view': 'Ver',
    'button.details': 'Detalles',
    'button.more': 'Más',
    'button.less': 'Menos',
    'button.expand': 'Expandir',
    'button.collapse': 'Contraer',
    'button.yes': 'Sí',
    'button.no': 'No',
    'button.ok': 'OK',
    'button.got.it': 'Entendido',
    'button.learn.more': 'Aprender más',
    'button.get.started': 'Comenzar',
    'button.try.now': 'Probar ahora',
    'button.buy.now': 'Comprar ahora',
    'button.add': 'Agregar',
    'button.remove': 'Quitar',
    'button.update': 'Actualizar',
    'button.create': 'Crear',
    'button.deploy': 'Desplegar',
    'button.verify': 'Verificar',
    'button.dashboard': 'Ir al Tablero',
    'button.preview': 'Vista previa',
    'button.export': 'Exportar',
    'button.import': 'Importar',
    
    // Common Labels
    'label.name': 'Nombre',
    'label.email': 'Correo electrónico',
    'label.password': 'Contraseña',
    'label.username': 'Nombre de usuario',
    'label.address': 'Dirección',
    'label.wallet': 'Billetera',
    'label.balance': 'Balance',
    'label.amount': 'Cantidad',
    'label.total': 'Total',
    'label.status': 'Estado',
    'label.type': 'Tipo',
    'label.date': 'Fecha',
    'label.time': 'Hora',
    'label.description': 'Descripción',
    'label.title': 'Título',
    'label.category': 'Categoría',
    'label.tags': 'Etiquetas',
    'label.price': 'Precio',
    'label.quantity': 'Cantidad',
    'label.available': 'Disponible',
    'label.pending': 'Pendiente',
    'label.completed': 'Completado',
    'label.failed': 'Fallido',
    'label.active': 'Activo',
    'label.inactive': 'Inactivo',
    'label.enabled': 'Habilitado',
    'label.disabled': 'Deshabilitado',
    'label.online': 'En línea',
    'label.offline': 'Desconectado',
    'label.connected': 'Conectado',
    'label.disconnected': 'Desconectado',
    'label.loading': 'Cargando...',
    'label.processing': 'Procesando...',
    'label.success': 'Éxito',
    'label.error': 'Error',
    'label.warning': 'Advertencia',
    'label.info': 'Información',
    
    // Messages
    'message.success': 'Operación completada exitosamente',
    'message.error': 'Ocurrió un error',
    'message.loading': 'Cargando, por favor espere...',
    'message.no.data': 'No hay datos disponibles',
    'message.coming.soon': 'Próximamente',
    'message.under.construction': 'En construcción',
    'message.not.found': 'No encontrado',
    'message.unauthorized': 'Acceso no autorizado',
    'message.forbidden': 'Acceso prohibido',
    'message.server.error': 'Error del servidor',
    'message.network.error': 'Error de red',
    'message.timeout': 'Tiempo de espera agotado',
    'message.invalid.input': 'Entrada inválida',
    'message.required.field': 'Este campo es requerido',
    'message.confirm.action': '¿Está seguro que desea continuar?',
    'message.unsaved.changes': 'Tiene cambios sin guardar',
    'message.copied': 'Copiado al portapapeles',
    'message.saved': 'Cambios guardados',
    'message.deleted': 'Eliminado exitosamente',
    
    // Treasury Page
    'treasury.title': 'Tesorería XMRT',
    'treasury.description': 'Compra cripto y ve estadísticas de la tesorería',
    'treasury.purchase.title': 'Comprar Cripto',
    'treasury.stats.title': 'Estadísticas de Tesorería',
    'treasury.stats.tvl': 'Valor Total Bloqueado',
    'treasury.stats.contributors': 'Contribuyentes',
    
    // Mining Calculator
    'calculator.info.title': 'Información MobileMonero',
    'calculator.info.description': 'MobileMonero.com es la primera plataforma de minería Monero móvil diseñada para smartphones y tablets.',
    'calculator.info.empowering': 'Empodera a los usuarios a participar en minería de criptomonedas usando procesadores ARM.',
    'calculator.mining.title': 'Calculadora de Minería MobileMonero',
    'calculator.hashrate.label': 'Hashrate del Dispositivo',
    'calculator.devices.label': 'Número de Dispositivos de Minería',
    'calculator.price.label': 'Precio de Monero (USD)',
    'calculator.network.title': 'Estadísticas de Red',
    'calculator.network.hashrate': 'Hashrate Total de Red',
    'calculator.network.share': 'Tu Participación en Red',
    'calculator.network.price': 'Precio XMR',
    'calculator.earnings.title': 'Ganancias Proyectadas',
    'calculator.earnings.daily': 'Diario',
    'calculator.earnings.monthly': 'Mensual',
    'calculator.earnings.yearly': 'Anual',
    'calculator.disclaimer': 'Estos cálculos son estimaciones basadas en la dificultad actual de la red y pueden variar significativamente. Los resultados reales de minería dependen del rendimiento del dispositivo, condiciones de red y factores de mercado.',
    
    // Mining Stats
    'stats.title': 'Estadísticas de Minería en Vivo',
    'stats.hashrate': 'Hashrate Actual',
    'stats.shares': 'Shares Válidos',
    'stats.invalid.shares': 'Shares Inválidos',
    'stats.amount.due': 'Cantidad Adeudada',
    'stats.amount.paid': 'Cantidad Pagada',
    'stats.transactions': 'Transacciones',
    'stats.last.hash': 'Último Hash',
    'stats.total.hashes': 'Hashes Totales',
    'stats.status.online': 'En Línea',
    'stats.status.offline': 'Desconectado',
    'stats.last.update': 'Última Actualización',
    'stats.retry': 'Reintentar Conexión',
    'stats.demo.mode': 'Modo Demo',
    'stats.ago': 'hace',
    
    // Chat Interface
    'chat.error.microphone': 'No se puede acceder al micrófono',
    'chat.error.connection': 'Error de conexión',
    'chat.error.network': 'Error de red',
    'chat.status.connecting': 'Conectando...',
    'chat.status.connected': 'Conectado',
    'chat.status.disconnected': 'Desconectado',
    'chat.status.listening': 'Escuchando...',
    'chat.status.speaking': 'Hablando...',
    'chat.button.start': 'Iniciar Conversación',
    'chat.button.stop': 'Detener',
    'chat.button.retry': 'Reintentar',
    'chat.permissions.needed': 'Se necesita permiso del micrófono',
    
    // DAO Tabs
    'dao.tabs.members': 'Miembros',
    'dao.tabs.xmrt': 'XMRT',
    'dao.tabs.governance': 'Gobernanza',
    'dao.tabs.treasury': 'Tesorería',
    'dao.tabs.proposals': 'Propuestas',
    'dao.tabs.discussions': 'Discusiones',
    
    // XMRT Faucet
    'faucet.title': 'Faucet de Tokens XMRT',
    'faucet.description': 'Reclama tokens XMRT gratuitos en la testnet Sepolia',
    'faucet.network.status': 'Estado de Red',
    'faucet.network.correct': 'Conectado a Sepolia',
    'faucet.network.wrong': 'Cambiar a Testnet Sepolia',
    'faucet.claim.amount': 'Cantidad a Reclamar',
    'faucet.claim.status': 'Estado de Reclamo',
    'faucet.claim.available': 'Disponible para reclamar',
    'faucet.claim.cooldown': 'Tiempo de espera activo',
    'faucet.claim.button': 'Reclamar XMRT',
    'faucet.claim.next': 'Próximo reclamo disponible en',
    'faucet.success': '¡Tokens XMRT reclamados exitosamente!',
    'faucet.error': 'Error al reclamar tokens. Intenta de nuevo.',
    'faucet.error.network': 'Por favor conecta primero a la testnet Sepolia.',
    
    // Mobile Monero Calculator Info Sections
    'calculator.info.how.works': 'Cómo Funciona',
    'calculator.info.how.works.point1': 'Procesadores móviles avanzados minan Monero de manera óptima',
    'calculator.info.how.works.point2': 'SSB (Batería de Estado Sólido) permite sostener 3-5+ KH/s',
    'calculator.info.how.works.point3': 'Recompensas de minería financian operaciones del DAO XMRT',
    'calculator.info.how.works.point4': 'Red descentralizada de mineros móviles de alto rendimiento',
    'calculator.info.how.works.point5': 'Optimización ARM para máxima eficiencia',
    
    'calculator.info.dao.benefits': 'Beneficios del DAO',
    'calculator.info.dao.benefits.point1': 'Tesorería auto-sostenible a través de ingresos de minería',
    'calculator.info.dao.benefits.point2': 'Gobernanza democrática impulsada por participantes de minería',
    'calculator.info.dao.benefits.point3': 'Eficiencia ambiental a través de dispositivos móviles',
    'calculator.info.dao.benefits.point4': 'Accesibilidad global sin hardware especializado',
    
    // Workflow Steps
    'workflow.title': 'Pasos de Creación de Activos',
    'workflow.description': 'Sigue estos pasos para crear tu activo {type}',
    'workflow.start': 'Comenzar a Crear',
    'workflow.image.step1': 'Crear un contrato base ERC-721 o ERC-1155 para eficiencia óptima de gas',
    'workflow.image.step2': 'Sube tu archivo de imagen (PNG, JPG, GIF)',
    'workflow.image.step3': 'Establece propiedades de imagen (dimensiones, resolución)',
    'workflow.image.step4': 'Agrega metadatos (título, descripción, atributos)',
    'workflow.image.step5': 'Previsualiza tu NFT',
    'workflow.code.step1': 'Despliega un contrato factory para despliegue eficiente de contratos',
    'workflow.code.step2': 'Sube o pega tu código de contrato inteligente',
    'workflow.code.step3': 'Configura parámetros del contrato',
    'workflow.code.step4': 'Prueba funcionalidad del contrato',
    'workflow.code.step5': 'Despliega y verifica contrato',
    'workflow.document.step1': 'Inicializa un contrato ERC-721 con características de gestión de documentos',
    'workflow.document.step2': 'Sube tu documento (PDF, DOC)',
    'workflow.document.step3': 'Establece permisos de acceso',
    'workflow.document.step4': 'Agrega configuraciones de control de versión',
    'workflow.document.step5': 'Configura opciones de compartir',
    'workflow.audio.step1': 'Configura un contrato ERC-721 optimizado para NFTs de audio',
    'workflow.audio.step2': 'Sube tu archivo de audio (MP3, WAV)',
    'workflow.audio.step3': 'Establece propiedades de audio (bitrate, duración)',
    'workflow.audio.step4': 'Agrega información de pista',
    'workflow.audio.step5': 'Configura ajustes de reproducción',
    'landing.hero.title.part1': 'Reemplaza tu',
    'landing.hero.title.part2': 'C-Suite',
    'landing.hero.title.part3': 'No a tus trabajadores',
    'landing.hero.subtitle': 'Consejo Ejecutivo de IA que ahorra $12.4M anualmente mientras permite aumentos salariales del 41% para sus empleados.',
    'landing.hero.start.trial': 'Iniciar prueba gratuita',
    'landing.hero.watch.demo': 'Ver demostración',
    'landing.stats.savings': 'Ahorro promedio de C-Suite',
    'landing.stats.salary': 'Aumento salarial de empleados',
    'landing.stats.functions': 'Funciones autónomas',
    'landing.stats.operations': 'Operaciones siempre activas',
    'landing.executives.title': 'Conoce a tu Consejo Ejecutivo de IA',
    'landing.executives.subtitle': 'Cinco ejecutivos de IA especializados trabajan juntos las 24 horas, los 7 días de la semana, tomando decisiones estratégicas y ejecutando flujos de trabajo autónomos.',
    'landing.benefits.title': '¿Por qué elegir Suite AI?',
    'landing.benefits.subtitle': 'IA ética que empodera a los trabajadores, no los reemplaza.',
    'landing.benefits.cost.title': 'Ahorros de costos masivos',
    'landing.benefits.cost.desc': 'Promedio de $12.4M ahorrados al reemplazar salarios costosos de C-suite con ejecutivos de IA.',
    'landing.benefits.empowerment.title': 'Empoderamiento de los empleados',
    'landing.benefits.empowerment.desc': 'Ahorros redistribuidos como aumentos salariales promedio del 41% para los trabajadores.',
    'landing.benefits.autonomous.title': 'Operaciones autónomas',
    'landing.benefits.autonomous.desc': 'Más de 120 funciones de borde ejecutan tareas las 24 horas, los 7 días de la semana sin intervención humana.',
    'landing.trial.title': 'para comenzar tu prueba gratuita',
    'landing.trial.no.card': 'No se requiere tarjeta de crédito',
    'landing.trial.cta': 'Comenzar ahora',
    'landing.how.title': 'Cómo funciona',
    'landing.how.subtitle': 'Comienza en minutos, no en meses.',
    'landing.how.step1.title': 'Regístrate',
    'landing.how.step1.desc': 'Crea tu cuenta en segundos con Google',
    'landing.how.step2.title': 'Chatea con ejecutivos',
    'landing.how.step2.desc': 'Describe tus necesidades a los miembros del consejo de IA',
    'landing.how.step3.title': 'Míralo funcionar',
    'landing.how.step3.desc': 'Agentes autónomos ejecutan tareas en tiempo real',
    'footer.copyright': '© 2026 XMRT-DAO. Todos los derechos reservados.',
    'footer.privacy': 'Política de privacidad',
    'footer.terms': 'Términos de servicio',
    'dashboard.visualizer.title': 'Visualizador de agentes y tareas',
    'dashboard.activity.title': 'Actividad del sistema',
    'dashboard.activity.live': 'En vivo',
    'hero.banner.enterprise.title': 'Automatización de IA empresarial',
    'hero.banner.enterprise.subtitle': 'Sistemas inteligentes que trabajan mientras duermes',
    'hero.banner.functions.title': 'Más de 120 funciones de borde',
    'hero.banner.functions.subtitle': 'Infraestructura auto-reparable y auto-optimizada',
    'hero.banner.monitoring.title': 'Monitoreo en tiempo real',
    'hero.banner.monitoring.subtitle': 'Visibilidad completa de cada operación',
    'hero.banner.council.title': 'Consejo Ejecutivo de IA',
    'hero.banner.council.subtitle': 'Gobernanza y toma de decisiones autónomas',
    'hero.stats.executions': 'Ejecuciones totales',
    'hero.stats.agents': 'Agentes activos',
    'hero.stats.health': 'Salud del sistema',
    'hero.stats.tasks': 'Tareas activas',
    'hero.activity.title': 'Feed de actividad en vivo',
    'hero.activity.realtime': 'Tiempo real',
    'licensing.hero.badge': 'Licenciamiento de IA Ética',
    'licensing.hero.title': 'Reemplaza tu C-Suite, No a tus trabajadores',
    'licensing.hero.subtitle': 'Nuestra Junta Ejecutiva de IA ofrece capacidades de liderazgo de Fortune 500 a una fracción del costo. ¿La diferencia? El 100% de los ahorros van a sus empleados.',
    'licensing.stats.savings': 'Ahorro anual promedio',
    'licensing.stats.salary': 'Aumento salarial de empleados',
    'licensing.stats.executives': 'Ejecutivos de IA (CSO, CTO, CIO, CAO, COO)',
    'licensing.button.apply': 'Iniciar solicitud',
    'licensing.button.chat': 'Habla con Eliza en su lugar',
    'licensing.calculator.title': 'Calcula tus ahorros',
    'licensing.tiers.title': 'Elige tu nivel de licencia',
    'licensing.tiers.subtitle': 'Cada nivel incluye nuestro compromiso ético: los ahorros del reemplazo de ejecutivos de IA deben redistribuirse a los empleados, no a los accionistas.',
    'licensing.form.title': 'Solicitud de licencia corporativa',
    'licensing.form.subtitle': 'Complete este formulario para solicitar nuestro programa de licencias ejecutivas de IA ética.',
    'licensing.form.chat.prompt': '¿Prefieres conversar?',
    'licensing.form.chat.link': 'Deja que Eliza te guíe a través de ello.',
    'licensing.commitment.title': 'Nuestro compromiso ético',
    'licensing.commitment.p1': 'El modelo de licencia ejecutiva de IA de XMRT se basa en un principio simple: la IA debe mejorar a los humanos, no reemplazarlos.',
    'licensing.commitment.p2': 'Al licenciar a nuestros ejecutivos de IA, usted acepta nuestro mandato de redistribución descendente:',
    'licensing.commitment.li1': 'El 100% de los ahorros en compensación ejecutiva debe redistribuirse a los empleados',
    'licensing.commitment.li2': 'No se permiten despidos como condición de la licencia',
    'licensing.commitment.li3': 'Las auditorías de cumplimiento trimestrales aseguran la adherencia',
    'licensing.commitment.li4': 'Los informes de transparencia pública muestran su compromiso',
    'licensing.commitment.footer': 'Esto no es solo buena ética, es un buen negocio. Las empresas en nuestro programa reportan una mayor satisfacción de los empleados, una menor rotación y una mayor productividad.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};